@startuml
skinparam style strictuml
hide footbox

rectangle "Atendente: UI" as UI
rectangle "ServicoGestao" as Gestao
rectangle "KafkaProducer" as Producer
rectangle "RastreadorGateway" as Gateway

UI -> Gestao : 1: bloquearVeiculo(veiculoId)
Gestao -> Gestao : 1.1: validarStatusApolice()
Gestao -> Gestao : 1.2: atualizarStatusBanco(veiculoId, BLOQUEADO)
Gestao -> Producer : 1.3: enfileirarComando(imei, "CORTE_COMBUSTIVEL")
Producer -> Gateway : 1.4: publicarKafka(topico_comandos)
Gateway -> HW : 1.5: [MQTT Publish para HW]

@enduml
